#!/usr/bin/env bash

# This is a workaround to set the SELinux context of
# the greetd binary correctly. 
# (See: https://github.com/sidusIO/sediment/pull/26)

cp /usr/bin/greetd /usr/local/bin/greetd
mount --bind /usr/local/bin/greetd /usr/bin/greetd
semanage fcontext -a -t xdm_exec_t /usr/bin/greetd
restorecon /usr/bin/greetd
