name: build sidusio/sediment
on:
  schedule:
    - cron: "00 17 * * *" # build at 17:00 UTC every day 
                          # (20 minutes after last ublue images start building)
  push:
    branches:
      - main
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  pull_request:
  workflow_dispatch: # allow manually triggering builds

jobs:
  generate-tags:
    name: Generate Tags
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}

    steps:
      - id: tags
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            TAGS="pr-${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.sha }}"
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_name }}" == "main" ]; then
            TAGS="latest ${{ github.sha }}"
          fi
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

  build-image:
    name: Build Custom Image
    needs: generate-tags
    permissions:
      contents: read
      packages: write
      id-token: write
    # Ubuntu 24.04 has Podman 4 installed from scratch
    runs-on: ubuntu-24.04

    steps:
    - uses: sigstore/cosign-installer@v3.5.0
    - uses: actions/checkout@v4
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}/sediment
        containerfiles: Containerfile
        oci: true
        tags: ${{ needs.generate-tags.outputs.tags }}
