name: build sidusio/sediment
on:
  schedule:
    - cron: "00 17 * * *" # build at 17:00 UTC every day 
                          # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here 
          - recipe.yml
    steps:
      # clones user's repo
      - uses: actions/checkout@v4

      - run: |
          mkdir -p /tmp/gh
          echo "${{ github.ref_name }}" > /tmp/gh/ref_name
          echo "${{ github.event.pull_request.head.sha }}" > /tmp/gh/pr_head_sha
          echo "${{ github.sha }}" > /tmp/gh/sha

      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: .github/actions/blue-build
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
