on:
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  FEDORA_VERSION: 41

name: release-iso
jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ${{ github.event.repository.name }}
          image_repo: ${{ env.REGISTRY }}/${{ github.repository_owner }}
          image_tag: latest
          version: ${{ env.FEDORA_VERSION }}
          variant: ${{ github.event.repository.name }}
          iso_name: ${{ github.event.repository.name }}-${{ env.FEDORA_VERSION }}.iso

      - name: Upload ISO
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release list -R ${{ github.repository_owner }}/${{ github.event.repository.name }} | grep "auto-iso"; then
            gh release view auto-iso -R ${{ github.repository_owner }}/${{ github.event.repository.name }} --json assets -q .assets[].name | xargs -L 1 gh release delete-asset auto-iso -R ${{ github.repository_owner }}/${{ github.event.repository.name }}
            gh release upload auto-iso ${{ steps.build.outputs.iso_path }}${{ steps.build.outputs.iso_name }} -R ${{ github.repository_owner }}/${{ github.event.repository.name }} --clobber
          else
            gh release create auto-iso ${{ steps.build.outputs.iso_path }}${{ steps.build.outputs.iso_name }} -t ISO -n "This is an automatically generated ISO release." -R ${{ github.repository_owner }}/${{ github.event.repository.name }}
          fi
          gh release upload auto-iso ${{ steps.build.outputs.iso_path }}${{ steps.build.outputs.iso_name }}-CHECKSUM -R ${{ github.repository_owner }}/${{ github.event.repository.name }} --clobber
