on:
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  FEDORA_VERSION: 41

name: release-iso
jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ${{ github.event.repository.name }}
          image_repo: ${{ env.REGISTRY }}
          image_tag: ${{ github.sha }}
          version: ${{ env.FEDORA_VERSION }}
          variant: ${{ github.event.repository.name }}
          iso_name: ${{ github.event.repository.name }}-${{ env.FEDORA_VERSION }}-${{ env.FEDORA_VERSION }}.iso

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
